In [2]:
# todo 学習結果を使って運用するための環境を作る。

# 選手情報・過去レース情報から3連単舟券120種をクラス分類する
# LGBMでやってみる。
# todo:bayseの方と、インプットの与え方をあわせる。今はOne-Hotが一致していない。
# 的中予想確率x%以上のうち、オッズで見合うものだけ買った場合のシミュレーションをする。

# このnoteでは情報を増やしてみる。過去100レースの着順分布をいれる。m1rank1,m1rank2,…m1rank6,m2rank1,…,m6rank6
# 着順分布の取得が時間かかりすぎるので、期間を絞って開発する。★☆
# 期間を変えるときには、num_leavesも調整する。

# 汎用ライブラリのimport
import sys
import os
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np
import statsmodels.api as sm
import math
import tensorflow as tf
import collections

import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import csv
from itertools import chain

In [3]:
# 自作ライブラリのimport
if os.environ['BR_HOME']+"/boatrace" not in sys.path:
    sys.path.append(os.environ['BR_HOME']+"/boatrace")
#print(sys.path)

from setup.myUtil import dbHandler

In [4]:
# 舟券の配列を取得
funakenList=[]
with open(os.environ['BR_HOME']+'/boatrace/config/3t_list.dat') as f:
    reader=csv.reader(f)
    for row in reader:
        funakenList.append(row)
funakenID = [i for i in range(120)]
funakenDict=dict(zip(funakenList[0],funakenID))
#print(funakenDict)

In [5]:
# 分析期間の指定は一旦ここでまとめてみる。
trainStartDate="20170901"
trainEndDate="20190430"
# test はtrainからsplitする

In [6]:
dbh=dbHandler.getDBHandle()
#dbHandler.closeDBHandle(dbh)

In [7]:
# trainの元データを取得
with dbh.cursor() as cursor:
    sel_sql = "select * from raceabst_forml_v \
               where raceDate between '%s' and '%s' \
               order by raceId "\
               % (trainStartDate,trainEndDate)
    cursor.execute(sel_sql)
    loadList=cursor.fetchall()
print("traindata:",len(loadList))

traindata: 549

In [8]:
# 過去成績をjoinする
oldResultList=[]
progressCounter=0
with dbh.cursor() as racecursor:
    for raceId in [ loadList[i]['raceId'] for i in range(len(loadList))]:
        progressCounter+=1
        if progressCounter % 1000 == 0:
            print("progress:",progressCounter/len(loadList))
        with dbh.cursor() as membercursor:
            #raceIdから登録番号のリストを取得
            selmember_sql = "select rmToban from racemember where raceId = '%s' order by rmLane" % (raceId)
            membercursor.execute(selmember_sql)
            tmpMemList=membercursor.fetchall()
            with dbh.cursor() as oldResultCursor:
                tmpOldDict={'raceId':raceId}
                lane=1
                for tobanHash in tmpMemList:
                    # あとでまた変換するのが面倒だから、変数名をレーン別にわける。
                    sel_sql = "select \
                                   count(CASE WHEN a.goalRank=1 THEN a.goalRank END)/100 as lane"+str(lane)+"oldRank1,\
                                   count(CASE WHEN a.goalRank=2 THEN a.goalRank END)/100 as lane"+str(lane)+"oldRank2,\
                                   count(CASE WHEN a.goalRank=3 THEN a.goalRank END)/100 as lane"+str(lane)+"oldRank3,\
                                   count(CASE WHEN a.goalRank=4 THEN a.goalRank END)/100 as lane"+str(lane)+"oldRank4,\
                                   count(CASE WHEN a.goalRank=5 THEN a.goalRank END)/100 as lane"+str(lane)+"oldRank5,\
                                   count(CASE WHEN a.goalRank=6 THEN a.goalRank END)/100 as lane"+str(lane)+"oldRank6 \
                               from ( \
                                    select tr.goalRank from raceresult tr\
                                    where tr.toban = '%s' \
                                    and tr.raceId < '%s'\
                                    order by tr.raceId desc \
                                    limit 100 \
                                   ) a "\
                                % (tobanHash['rmToban'],raceId)
                    oldResultCursor.execute(sel_sql)
                    # 辞書型で、6レーン分を順次結合
                    tmpOldDict.update( (oldResultCursor.fetchall())[0] )
                    lane+=1
                # 終わったらraceId別にList型でまとめる
                oldResultList.append(tmpOldDict)
print("oldResultList:",len(oldResultList))
#print(oldResultList[0:5])

oldResultList: 549

In [9]:
df_member = pd.io.json.json_normalize(loadList)
df_oldResult = pd.io.json.json_normalize(oldResultList)
for lane in range(1,6+1):
    for Rank in range(1,6+1):
        key="lane"+str(lane)+"oldRank"+str(Rank)
        df_oldResult[key]=df_oldResult[key].astype(np.float)
df = pd.merge(df_member,df_oldResult,on='raceId',how='inner')
df.head()

,funaken,l1Fcnt,l1boat2r,l1boat3r,l1motor2r,l1motor3r,l1rank,l1score,l2Fcnt,l2boat2r,...,lane5oldRank3,lane5oldRank4,lane5oldRank5,lane5oldRank6,lane6oldRank1,lane6oldRank2,lane6oldRank3,lane6oldRank4,lane6oldRank5,lane6oldRank6
0,1-3-2,0,0.3196,0.4639,0.3563,0.5287,B2,7.146175,1,0.2525,...,0.17,0.18,0.13,0.18,0.14,0.15,0.11,0.14,0.15,0.31
1,6-1-3,0,0.3918,0.5361,0.2727,0.4416,B1,14.019347,0,0.2917,...,0.21,0.15,0.23,0.22,0.03,0.09,0.14,0.24,0.19,0.31
2,5-2-6,0,0.3333,0.5152,0.2985,0.4776,B1,8.495094,1,0.3021,...,0.16,0.19,0.17,0.21,0.16,0.21,0.17,0.17,0.16,0.13
3,2-6-3,1,0.4479,0.6354,0.3919,0.5541,A2,4.171185,0,0.2268,...,0.06,0.05,0.23,0.62,0.34,0.20,0.17,0.15,0.07,0.07
4,1-5-4,1,0.4490,0.6224,0.5857,0.7714,A2,5.128468,0,0.4021,...,0.13,0.13,0.17,0.22,0.08,0.12,0.14,0.27,0.24,0.15

In [10]:
# 入力のデータ整形
#xdf=df.drop(['funaken','odds','raceId','raceDate'],axis=1)
#xdf=pd.get_dummies(xdf,columns=['l1rank','l2rank','l3rank','l4rank','l5rank','l6rank'])
#xdf.head()

# 入力のデータ整形
xdf=df.drop(['funaken','odds','raceId','raceDate'],axis=1)
#xdf=pd.get_dummies(xdf,columns=['l1rank','l2rank','l3rank','l4rank','l5rank','l6rank'])
rankLabel=LabelEncoder()
rankLabel=rankLabel.fit(xdf['l1rank'])
xdf['l1rank']=rankLabel.transform(xdf['l1rank'])
xdf['l2rank']=rankLabel.transform(xdf['l2rank'])
xdf['l3rank']=rankLabel.transform(xdf['l3rank'])
xdf['l4rank']=rankLabel.transform(xdf['l4rank'])
xdf['l5rank']=rankLabel.transform(xdf['l5rank'])
xdf['l6rank']=rankLabel.transform(xdf['l6rank'])
xdf.head()

,l1Fcnt,l1boat2r,l1boat3r,l1motor2r,l1motor3r,l1rank,l1score,l2Fcnt,l2boat2r,l2boat3r,...,lane5oldRank3,lane5oldRank4,lane5oldRank5,lane5oldRank6,lane6oldRank1,lane6oldRank2,lane6oldRank3,lane6oldRank4,lane6oldRank5,lane6oldRank6
0,0,0.3196,0.4639,0.3563,0.5287,3,7.146175,1,0.2525,0.3838,...,0.17,0.18,0.13,0.18,0.14,0.15,0.11,0.14,0.15,0.31
1,0,0.3918,0.5361,0.2727,0.4416,2,14.019347,0,0.2917,0.4167,...,0.21,0.15,0.23,0.22,0.03,0.09,0.14,0.24,0.19,0.31
2,0,0.3333,0.5152,0.2985,0.4776,2,8.495094,1,0.3021,0.5313,...,0.16,0.19,0.17,0.21,0.16,0.21,0.17,0.17,0.16,0.13
3,1,0.4479,0.6354,0.3919,0.5541,1,4.171185,0,0.2268,0.4124,...,0.06,0.05,0.23,0.62,0.34,0.20,0.17,0.15,0.07,0.07
4,1,0.4490,0.6224,0.5857,0.7714,1,5.128468,0,0.4021,0.5567,...,0.13,0.13,0.17,0.22,0.08,0.12,0.14,0.27,0.24,0.15

In [11]:
xdf.describe()
#print(xdf['l1boat2r'].describe())
#print(xdf['lane1oldRank1'].describe())
#print(xdf['lane6oldRank6'].describe())

,l1Fcnt,l1boat2r,l1boat3r,l1motor2r,l1motor3r,l1rank,l1score,l2Fcnt,l2boat2r,l2boat3r,...,lane5oldRank3,lane5oldRank4,lane5oldRank5,lane5oldRank6,lane6oldRank1,lane6oldRank2,lane6oldRank3,lane6oldRank4,lane6oldRank5,lane6oldRank6
count,549.000000,549.000000,549.000000,549.00000,549.000000,549.000000,549.000000,549.000000,549.000000,549.000000,...,549.000000,549.000000,549.000000,549.000000,549.000000,549.000000,549.000000,549.000000,549.000000,549.000000
mean,0.296903,0.306568,0.454677,0.32669,0.483303,1.049180,12.890804,0.289617,0.295831,0.444281,...,0.162568,0.164809,0.172987,0.189672,0.139326,0.146958,0.155610,0.160692,0.171330,0.206412
std,0.484438,0.146010,0.187754,0.12585,0.160096,0.895724,8.210162,0.473670,0.141867,0.193207,...,0.058085,0.055225,0.062562,0.139860,0.098058,0.071606,0.063068,0.059258,0.059929,0.154998
min,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,2.012032,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.030000,0.010000,0.000000,0.000000,0.000000,0.000000,0.020000,0.020000
25%,0.000000,0.285700,0.445700,0.29050,0.438100,0.000000,6.244536,0.000000,0.273300,0.440000,...,0.140000,0.130000,0.130000,0.100000,0.070000,0.110000,0.130000,0.120000,0.130000,0.110000
50%,0.000000,0.333300,0.500000,0.33730,0.510800,1.000000,11.101859,0.000000,0.330300,0.497700,...,0.170000,0.170000,0.170000,0.150000,0.120000,0.150000,0.160000,0.160000,0.170000,0.160000
75%,1.000000,0.375700,0.553200,0.38420,0.568400,2.000000,17.830080,1.000000,0.373100,0.549500,...,0.200000,0.200000,0.210000,0.220000,0.200000,0.200000,0.200000,0.200000,0.210000,0.240000
max,2.000000,1.000000,1.000000,0.76470,0.875000,3.000000,48.590865,2.000000,1.000000,1.000000,...,0.300000,0.310000,0.370000,0.840000,0.440000,0.300000,0.320000,0.330000,0.340000,0.860000

In [12]:
# ファイルから作った辞書で変換する
ydf=df['funaken']
ydf=pd.DataFrame(ydf.replace(funakenDict))
ydf['funaken']=ydf['funaken'].astype(int)
#print(ydf.head())
print(ydf['funaken'].dtype)

int64

In [13]:
# 重み付けのため、オッズのリストを作る
odf=df['odds'].values
#odf=pd.DataFrame(df['odds'])
#odf.describe()
#print(odf)

In [14]:
X_train, X_test, y_train, y_test,o_train,o_test = train_test_split(xdf, ydf,odf)
print("X_train,X_test:",len(X_train),len(X_test))

X_train,X_test: 411 138

In [15]:
lgb_train = lgb.Dataset(X_train, y_train)
lgb_eval = lgb.Dataset(X_test, y_test, reference=lgb_train)

In [16]:
lgbm_params = {
    # 多値分類問題
    'objective': 'multiclass',
    # クラス数は 120
    'num_class': 120,
    #'class_weight':'balanced',
    #'random_state':999,
    # 以下、ハイパーパラメタ
    'max_depth':3,
    'num_leaves':6,
    'min_data_in_leaf':300,
    # 正則化
    'reg_alpha':2.425,
    'reg_lambda':9.473 ,
}

In [17]:
lgb.LGBMClassifier()

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='split', learning_rate=0.1, max_depth=-1,
        min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
        n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
        random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
        subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [18]:
model = lgb.train(lgbm_params, lgb_train, valid_sets=lgb_eval)

[1]	valid_0's multi_logloss: 6.28298
[2]	valid_0's multi_logloss: 6.26617
[3]	valid_0's multi_logloss: 6.25041
[4]	valid_0's multi_logloss: 6.23325
[5]	valid_0's multi_logloss: 6.21839
[6]	valid_0's multi_logloss: 6.20508
[7]	valid_0's multi_logloss: 6.19003
[8]	valid_0's multi_logloss: 6.17745
[9]	valid_0's multi_logloss: 6.16766
[10]	valid_0's multi_logloss: 6.15783
[11]	valid_0's multi_logloss: 6.14652
[12]	valid_0's multi_logloss: 6.13513
[13]	valid_0's multi_logloss: 6.12645
[14]	valid_0's multi_logloss: 6.11767
[15]	valid_0's multi_logloss: 6.11037
[16]	valid_0's multi_logloss: 6.10405
[17]	valid_0's multi_logloss: 6.09757
[18]	valid_0's multi_logloss: 6.09237
[19]	valid_0's multi_logloss: 6.08495
[20]	valid_0's multi_logloss: 6.07996
[21]	valid_0's multi_logloss: 6.07486
[22]	valid_0's multi_logloss: 6.06982
[23]	valid_0's multi_logloss: 6.06599
[24]	valid_0's multi_logloss: 6.06196
[25]	valid_0's multi_logloss: 6.05487
[26]	valid_0's multi_logloss: 6.05221
[27]	valid_0's multi_logloss: 6.04782
[28]	valid_0's multi_logloss: 6.04638
[29]	valid_0's multi_logloss: 6.04159
[30]	valid_0's multi_logloss: 6.03855
[31]	valid_0's multi_logloss: 6.03511
[32]	valid_0's multi_logloss: 6.03167
[33]	valid_0's multi_logloss: 6.02887
[34]	valid_0's multi_logloss: 6.02498
[35]	valid_0's multi_logloss: 6.02334
[36]	valid_0's multi_logloss: 6.02151
[37]	valid_0's multi_logloss: 6.01856
[38]	valid_0's multi_logloss: 6.01818
[39]	valid_0's multi_logloss: 6.01394
[40]	valid_0's multi_logloss: 6.01199
[41]	valid_0's multi_logloss: 6.00976
[42]	valid_0's multi_logloss: 6.00793
[43]	valid_0's multi_logloss: 6.00775
[44]	valid_0's multi_logloss: 6.00793
[45]	valid_0's multi_logloss: 6.00571
[46]	valid_0's multi_logloss: 6.00354
[47]	valid_0's multi_logloss: 6.00209
[48]	valid_0's multi_logloss: 5.99969
[49]	valid_0's multi_logloss: 5.99981
[50]	valid_0's multi_logloss: 5.99833
[51]	valid_0's multi_logloss: 5.99856
[52]	valid_0's multi_logloss: 5.99758
[53]	valid_0's multi_logloss: 5.99632
[54]	valid_0's multi_logloss: 5.99433
[55]	valid_0's multi_logloss: 5.996
[56]	valid_0's multi_logloss: 5.99484
[57]	valid_0's multi_logloss: 5.99407
[58]	valid_0's multi_logloss: 5.99415
[59]	valid_0's multi_logloss: 5.99228
[60]	valid_0's multi_logloss: 5.99223
[61]	valid_0's multi_logloss: 5.99113
[62]	valid_0's multi_logloss: 5.99143
[63]	valid_0's multi_logloss: 5.9915
[64]	valid_0's multi_logloss: 5.9912
[65]	valid_0's multi_logloss: 5.98969
[66]	valid_0's multi_logloss: 5.98874
[67]	valid_0's multi_logloss: 5.98918
[68]	valid_0's multi_logloss: 5.98831
[69]	valid_0's multi_logloss: 5.98714
[70]	valid_0's multi_logloss: 5.98775
[71]	valid_0's multi_logloss: 5.98595
[72]	valid_0's multi_logloss: 5.98561
[73]	valid_0's multi_logloss: 5.98529
[74]	valid_0's multi_logloss: 5.9855
[75]	valid_0's multi_logloss: 5.98565
[76]	valid_0's multi_logloss: 5.98576
[77]	valid_0's multi_logloss: 5.98511
[78]	valid_0's multi_logloss: 5.9856
[79]	valid_0's multi_logloss: 5.98525
[80]	valid_0's multi_logloss: 5.98458
[81]	valid_0's multi_logloss: 5.98532
[82]	valid_0's multi_logloss: 5.98485
[83]	valid_0's multi_logloss: 5.98402
[84]	valid_0's multi_logloss: 5.98389
[85]	valid_0's multi_logloss: 5.98431
[86]	valid_0's multi_logloss: 5.98433
[87]	valid_0's multi_logloss: 5.98343
[88]	valid_0's multi_logloss: 5.98407
[89]	valid_0's multi_logloss: 5.98402
[90]	valid_0's multi_logloss: 5.98396
[91]	valid_0's multi_logloss: 5.98381
[92]	valid_0's multi_logloss: 5.98401
[93]	valid_0's multi_logloss: 5.98407
[94]	valid_0's multi_logloss: 5.98368
[95]	valid_0's multi_logloss: 5.98302
[96]	valid_0's multi_logloss: 5.98329
[97]	valid_0's multi_logloss: 5.98434
[98]	valid_0's multi_logloss: 5.98446
[99]	valid_0's multi_logloss: 5.98261
[100]	valid_0's multi_logloss: 5.98283

In [19]:
y_pred = model.predict(X_test, num_iteration=model.best_iteration)
y_pred_max = np.argmax(y_pred, axis=1)  # 最尤と判断したクラスの値にする

# 精度 (Accuracy) を計算する
accuracy = sum(y_test['funaken'] == y_pred_max) / len(y_test)
print("accuracy:",accuracy)

# 回収率を計算
res=0
for i in range(len(y_test)):
    if (y_test.iloc[i])['funaken']==y_pred_max[i]:
        #print("i:",i,"result:",y_test[i],"forecast:",y_pred_max[i],"forecastProb:",y_pred[i][y_pred_max[i]],"return:",o_test[i],"expect:",y_pred[i][y_pred_max[i]]*o_test[i])
        res += o_test[i] -1
    else:
        #print("i:",i,"result:",y_test[i],"forecast:",y_pred_max[i],"forecastProb:",y_pred[i][y_pred_max[i]],"return:",o_test[i],"expect:",y_pred[i][y_pred_max[i]]*o_test[i])
        pass
print("resultReturn:",res/len(y_test))

accuracy: 0.043478260869565216
resultReturn: 1.6420289855072463

In [20]:
print(len(y_pred))
# オッズを見て判断する場合
resAmount=0
buyAmount=0

dfIndexList=y_test['funaken'].index
for i in range(len(y_test)):
    raceId = df.iloc[dfIndexList[i]]['raceId']
    #print(raceId)
    with dbh.cursor() as cursor:
        sel_sql = "select funaken,odds from raceodds \
                   where oddsType = '3t' \
                   and raceId = '%s' \
                   order by funaken" \
                   % (raceId)
        cursor.execute(sel_sql)
        loadList=pd.DataFrame(cursor.fetchall())
        loadList=pd.DataFrame(loadList.replace(funakenDict))
    #print((loadList[loadList['funaken']==0]['odds'] * y_pred[i][0] ).values[0] )
    #if ( (loadList[loadList['funaken']==0]['odds'] * y_pred[i][0] ).values[0] > 1) :
    #    print("ok")
    #print(y_pred[i][0])
    #print(raceId)
    for j in range(120):
        if y_pred[i][j]> 0.10 and ( (y_pred[i][j] * (loadList[loadList['funaken']==j]['odds'])).values[0] > 1.5) :
            print("buy:",raceId,i,j,loadList[loadList['funaken']==j]['odds'].values[0])
            buyAmount+=1
            if y_test['funaken'].iloc[i]==j:
            #print("i:",i,"result:",y_test[i],"forecast:",y_pred_max[i],"forecastProb:",y_pred[i][y_pred_max[i]],"return:",o_test[i],"expect:",y_pred[i][y_pred_max[i]]*o_test[i])
                print("☆hit!☆:",raceId,j,loadList[loadList['funaken']==j]['odds'].values[0])
                resAmount += o_test[i]
            else:
            #print("i:",i,"result:",y_test[i],"forecast:",y_pred_max[i],"forecastProb:",y_pred[i][y_pred_max[i]],"return:",o_test[i],"expect:",y_pred[i][y_pred_max[i]]*o_test[i])
                pass
print("resultReturn:",resAmount/buyAmount)

138
buy: 20190429-12-01 3 16 92.8
buy: 20190429-13-10 7 2 38.2
buy: 20190430-09-12 11 20 30.6
buy: 20190430-18-05 13 7 173.3
buy: 20190429-20-04 16 20 40.1
buy: 20190430-07-03 20 0 9.1
buy: 20190428-16-04 26 7 115.6
☆hit!☆: 20190428-16-04 7 115.6
buy: 20190430-13-06 28 0 13.3
buy: 20190429-14-02 29 12 40.9
buy: 20190430-24-09 30 0 7.4
buy: 20190430-24-09 30 10 23.3
buy: 20190429-14-03 34 0 27.9
buy: 20190430-19-04 35 0 10.0
buy: 20190429-22-09 36 0 11.8
buy: 20190429-05-01 39 9 15.5
☆hit!☆: 20190429-05-01 9 15.5
buy: 20190430-20-12 48 4 15.2
buy: 20190428-16-08 50 5 69.3
buy: 20190428-16-01 52 3 13.5
buy: 20190429-11-05 53 1 56.7
buy: 20190430-14-06 58 9 26.0
buy: 20190429-24-03 60 20 8.4
buy: 20190430-09-02 63 20 61.7
☆hit!☆: 20190430-09-02 20 61.7
buy: 20190429-11-04 66 4 12.3
buy: 20190428-12-11 72 1 20.5
buy: 20190428-05-01 73 3 27.1
buy: 20190428-21-05 77 0 20.3
buy: 20190430-18-12 89 10 58.5
buy: 20190429-22-03 93 41 49.8
buy: 20190430-05-08 95 0 7.8
buy: 20190430-20-02 97 41 23.7
buy: 20190428-17-04 105 5 32.8
buy: 20190430-07-08 108 7 53.7
buy: 20190429-15-08 109 20 18.4
buy: 20190428-17-01 110 7 25.3
buy: 20190428-16-03 111 5 66.9
buy: 20190428-07-06 114 0 70.4
buy: 20190430-05-11 119 20 40.9
buy: 20190428-21-11 120 0 4.5
buy: 20190430-18-01 125 0 14.4
buy: 20190429-07-10 127 5 15.2
resultReturn: 4.82

In [21]:
print("totalRace,buy,return",len(y_test),buyAmount,resAmount )
# 現状でも100%はロバストに超えそう。
# だがrrが1.2でもbuyが6/300レースだと、1000円投票しても一日だと約3000*1.2⇒利益600円なので、もっと回収率を上げるか母数増やす。
# totalRace,buy,return 28274 608 614.3
# totalRace,buy,return 28274 614 804.8

totalRace,buy,return 138 40 192.8

In [23]:
print(len(y_pred))
# オッズを見て判断する場合
resAmount=0
buyAmount=0

dfIndexList=y_test['funaken'].index
for i in range(len(y_test)):
    raceId = df.iloc[dfIndexList[i]]['raceId']
    #print(raceId)
    with dbh.cursor() as cursor:
        sel_sql = "select funaken,odds from raceodds \
                   where oddsType = '3t' \
                   and raceId = '%s' \
                   order by funaken" \
                   % (raceId)
        cursor.execute(sel_sql)
        loadList=pd.DataFrame(cursor.fetchall())
        loadList=pd.DataFrame(loadList.replace(funakenDict))
    #print((loadList[loadList['funaken']==0]['odds'] * y_pred[i][0] ).values[0] )
    #if ( (loadList[loadList['funaken']==0]['odds'] * y_pred[i][0] ).values[0] > 1) :
    #    print("ok")
    #print(y_pred[i][0])
    #print(raceId)
    for j in range(120):
        # y_predの閾値を下げてみる。
        if y_pred[i][j]> 0.05 and ( (y_pred[i][j] * (loadList[loadList['funaken']==j]['odds'])).values[0] > 1.5) :
            print("buy:",raceId,i,j,loadList[loadList['funaken']==j]['odds'].values[0])
            buyAmount+=1
            if y_test['funaken'].iloc[i]==j:
            #print("i:",i,"result:",y_test[i],"forecast:",y_pred_max[i],"forecastProb:",y_pred[i][y_pred_max[i]],"return:",o_test[i],"expect:",y_pred[i][y_pred_max[i]]*o_test[i])
                print("☆hit!☆:",raceId,j,loadList[loadList['funaken']==j]['odds'].values[0])
                resAmount += o_test[i]
            else:
            #print("i:",i,"result:",y_test[i],"forecast:",y_pred_max[i],"forecastProb:",y_pred[i][y_pred_max[i]],"return:",o_test[i],"expect:",y_pred[i][y_pred_max[i]]*o_test[i])
                pass
print("resultReturn:",resAmount/buyAmount)
print("totalRace,buy,return",len(y_test),buyAmount,resAmount )
# y_pred[i][j]> 0.05に閾値下げてみた。投票数はかなり増えているが、回収率が低く、トータルリターンは下がっている。
# ToDo：運用に向けてはこのバランスを調整してみるのはあり。
#resultReturn: 1.005279187817259
#totalRace,buy,return 28274 4925 4951.0

138
buy: 20190429-08-03 2 100 374.8
buy: 20190429-12-01 3 16 92.8
buy: 20190428-05-08 5 4 63.0
buy: 20190428-05-08 5 100 146.0
buy: 20190429-15-11 6 3 25.8
buy: 20190429-13-10 7 2 38.2
buy: 20190428-12-10 8 10 26.8
☆hit!☆: 20190428-12-10 10 26.8
buy: 20190430-09-12 11 20 30.6
buy: 20190429-06-01 12 9 33.3
buy: 20190429-06-01 12 21 51.4
buy: 20190430-18-05 13 7 173.3
buy: 20190429-20-04 16 20 40.1
buy: 20190428-07-04 18 100 250.8
buy: 20190430-07-03 20 0 9.1
buy: 20190430-07-03 20 9 23.0
buy: 20190429-06-05 22 4 48.3
buy: 20190429-11-06 24 0 37.9
buy: 20190428-01-04 25 4 25.4
buy: 20190428-01-04 25 100 42.8
buy: 20190428-16-04 26 7 115.6
☆hit!☆: 20190428-16-04 7 115.6
buy: 20190429-14-01 27 1 28.0
buy: 20190429-14-01 27 2 82.7
buy: 20190430-13-06 28 0 13.3
buy: 20190429-14-02 29 2 32.1
buy: 20190429-14-02 29 12 40.9
buy: 20190430-24-09 30 0 7.4
buy: 20190430-24-09 30 10 23.3
buy: 20190429-14-03 34 0 27.9
buy: 20190430-19-04 35 0 10.0
buy: 20190429-22-09 36 0 11.8
buy: 20190430-18-02 38 12 18.5
buy: 20190429-05-01 39 9 15.5
☆hit!☆: 20190429-05-01 9 15.5
buy: 20190430-09-10 40 2 33.9
buy: 20190429-11-11 41 1 31.1
buy: 20190429-11-11 41 14 59.2
buy: 20190428-13-02 42 9 56.0
buy: 20190428-22-03 45 3 39.5
buy: 20190428-22-03 45 6 57.0
buy: 20190429-15-01 46 16 135.1
buy: 20190429-24-02 47 10 31.9
buy: 20190430-20-12 48 4 15.2
buy: 20190428-11-05 49 16 56.7
buy: 20190428-16-08 50 5 69.3
buy: 20190430-19-09 51 3 62.4
buy: 20190428-16-01 52 3 13.5
buy: 20190428-16-01 52 10 61.9
buy: 20190429-11-05 53 1 56.7
buy: 20190428-07-01 56 7 62.0
buy: 20190428-07-01 56 13 44.9
buy: 20190430-14-06 58 9 26.0
buy: 20190429-24-03 60 20 8.4
buy: 20190429-08-02 61 5 208.7
buy: 20190428-13-03 62 2 145.4
buy: 20190428-13-03 62 9 130.1
buy: 20190430-09-02 63 12 96.9
buy: 20190430-09-02 63 20 61.7
☆hit!☆: 20190430-09-02 20 61.7
buy: 20190430-09-02 63 100 79.1
buy: 20190429-11-04 66 4 12.3
buy: 20190429-11-04 66 56 44.2
buy: 20190429-13-01 69 4 16.7
buy: 20190429-13-01 69 9 344.4
buy: 20190429-14-11 71 3 36.3
buy: 20190428-12-11 72 1 20.5
buy: 20190428-12-11 72 10 53.2
buy: 20190428-05-01 73 3 27.1
buy: 20190428-05-01 73 7 49.9
buy: 20190429-06-08 75 1 27.3
buy: 20190428-21-05 77 0 20.3
buy: 20190428-21-05 77 9 47.8
buy: 20190428-15-06 80 0 34.7
buy: 20190428-15-06 80 7 34.1
buy: 20190428-15-06 80 100 32.2
buy: 20190430-11-12 81 16 46.3
buy: 20190429-21-03 82 0 74.4
buy: 20190429-21-03 82 10 67.8
buy: 20190428-08-04 85 5 38.7
buy: 20190429-21-05 86 14 165.2
buy: 20190429-11-01 88 0 33.8
buy: 20190430-18-12 89 10 58.5
buy: 20190428-05-04 92 4 284.0
buy: 20190429-22-03 93 41 49.8
buy: 20190430-05-08 95 0 7.8
buy: 20190430-20-02 97 4 42.2
buy: 20190430-20-02 97 41 23.7
buy: 20190428-17-10 101 14 581.3
buy: 20190428-17-04 105 5 32.8
buy: 20190429-07-06 106 0 50.3
buy: 20190429-07-06 106 1 53.0
buy: 20190429-07-06 106 4 36.4
buy: 20190429-08-01 107 9 322.5
buy: 20190430-07-08 108 7 53.7
buy: 20190429-15-08 109 9 57.1
buy: 20190429-15-08 109 20 18.4
buy: 20190428-17-01 110 7 25.3
buy: 20190428-17-01 110 10 28.5
buy: 20190428-16-03 111 1 36.4
buy: 20190428-16-03 111 5 66.9
buy: 20190428-24-09 113 5 33.1
buy: 20190428-07-06 114 0 70.4
buy: 20190428-07-06 114 1 18.3
buy: 20190430-21-10 117 14 64.8
buy: 20190428-14-03 118 62 103.6
buy: 20190430-05-11 119 20 40.9
buy: 20190428-21-11 120 0 4.5
buy: 20190428-11-07 121 9 23.8
buy: 20190428-01-03 123 4 21.1
buy: 20190430-18-01 125 0 14.4
buy: 20190428-06-10 126 14 112.0
buy: 20190429-07-10 127 5 15.2
buy: 20190429-12-10 129 3 23.0
buy: 20190430-20-01 131 7 16.6
buy: 20190430-20-01 131 41 58.5
buy: 20190429-15-04 133 100 86.2
buy: 20190430-18-11 134 10 18.7
buy: 20190430-18-11 134 62 26.8
buy: 20190430-15-11 135 14 17.3
buy: 20190428-06-02 136 7 219.4
resultReturn: 1.8769230769230771
totalRace,buy,return 138 117 219.60000000000002

In [25]:
# trainの回収率を計算
y_pred = model.predict(X_train, num_iteration=model.best_iteration)
y_pred_max = np.argmax(y_pred, axis=1)  # 最尤と判断したクラスの値にする

#print(X_train.head())
#print(y_train[0:5])
#print(y_pred_max[0:5])
#c = collections.Counter(y_pred_max)
#print(len(c) )

# 精度 (Accuracy) を計算する
# エラーになるけど気にしない。
#accuracy = sum(y_train == y_pred_max) / len(y_train)
#print("accuracy:",accuracy)

# 回収率を計算
#res=0
#for i in range(len(y_train)):
#    if y_train.iloc[i]==y_pred_max[i]:
#        res += o_train[i] -1
#    else:
#        pass
#print("return:",res/len(y_train))

In [26]:
print(y_pred[0])

[1.25290632e-02 3.23461445e-02 9.35941910e-03 2.68106673e-02
 1.42177568e-02 9.13812470e-03 1.62445809e-02 6.41411816e-03
 8.11550144e-03 2.80802036e-02 3.52615705e-01 6.21191396e-03
 8.99168336e-03 6.04537731e-03 8.77980433e-03 5.26664475e-03
 7.65952963e-03 7.00593683e-03 6.21227273e-03 4.89508145e-03
 7.72782299e-03 8.04461536e-03 1.83789376e-02 5.53400204e-03
 5.58287673e-03 4.78522159e-03 5.84589594e-03 6.88179376e-18
 5.31703709e-03 5.91426248e-03 6.58389275e-03 5.69887548e-03
 5.27040405e-03 6.88179376e-18 5.95793901e-03 4.75825430e-03
 4.85481712e-03 5.27081749e-03 4.76228083e-03 6.88179376e-18
 5.64132517e-03 6.37487778e-03 6.14272038e-03 4.76838769e-03
 4.79402783e-03 4.84003445e-03 4.90097998e-03 5.95043614e-03
 4.81203587e-03 4.75075285e-03 4.94679542e-03 4.77651926e-03
 5.09403161e-03 5.60037489e-03 4.75657706e-03 5.26797315e-03
 5.60890074e-03 6.88179376e-18 6.88179376e-18 4.77373535e-03
 5.53913850e-03 5.95582916e-03 6.68425999e-03 4.83803718e-03
 1.10411143e-02 5.06740634e-03 6.23335700e-03 5.67169298e-03
 6.38613021e-03 5.56248404e-03 4.77134410e-03 5.03411519e-03
 6.88179376e-18 5.27084176e-03 4.77979807e-03 5.43219669e-03
 5.25100913e-03 4.75733541e-03 4.74983342e-03 5.17751003e-03
 6.88179376e-18 5.02696086e-03 5.09453100e-03 4.81305510e-03
 4.77960158e-03 4.81807584e-03 4.75243824e-03 4.75181921e-03
 6.88179376e-18 5.28949030e-03 4.82299465e-03 6.88179376e-18
 6.67652797e-03 6.88179376e-18 6.88179376e-18 4.76284161e-03
 4.75433765e-03 6.88179376e-18 6.88179376e-18 6.88179376e-18
 5.54497167e-03 4.88210516e-03 4.77873739e-03 4.77756537e-03
 6.88179376e-18 6.88179376e-18 6.05584719e-03 4.76928455e-03
 6.88179376e-18 6.88179376e-18 6.88179376e-18 6.88179376e-18
 4.75746289e-03 5.30509407e-03 6.88179376e-18 6.88179376e-18
 4.79591710e-03 4.75893984e-03 6.88179376e-18 6.88179376e-18]

In [27]:
print(df.iloc[X_train.index]['raceId'])

507    20190430-19-07
516    20190430-20-04
305    20190429-16-07
282    20190429-14-08
83     20190428-12-12
114    20190428-15-07
363    20190429-22-06
333    20190429-18-11
347    20190429-21-02
280    20190429-14-06
143    20190428-18-01
515    20190430-20-03
161    20190428-21-07
63     20190428-11-04
401    20190430-07-09
112    20190428-15-05
352    20190429-21-07
246    20190429-11-08
74     20190428-12-03
170    20190428-22-04
238    20190429-08-12
291    20190429-15-05
309    20190429-16-11
4      20190428-01-05
476    20190430-16-12
209    20190429-06-07
18     20190428-05-07
80     20190428-12-09
166    20190428-21-12
539    20190430-24-03
            ...
326    20190429-18-04
268    20190429-13-06
171    20190428-22-05
234    20190429-08-08
320    20190429-17-10
467    20190430-16-03
75     20190428-12-04
451    20190430-14-11
312    20190429-17-02
208    20190429-06-06
307    20190429-16-09
284    20190429-14-10
48     20190428-08-01
427    20190430-11-11
256    20190429-12-06
6      20190428-01-07
138    20190428-17-07
332    20190429-18-10
356    20190429-21-11
530    20190430-21-06
418    20190430-11-02
544    20190430-24-08
195    20190429-05-05
338    20190429-20-05
422    20190430-11-06
173    20190428-22-07
72     20190428-12-01
76     20190428-12-05
541    20190430-24-05
96     20190428-14-01
Name: raceId, Length: 411, dtype: object

In [28]:
print(model.feature_importance())

[ 36 355 212 142 247 159 270   7 231 141 246 171   1 735   8 176 115 377
 154  72 470  30 261 214 270 220  36 521  10 175 224  52 234   2 270 147
 149 197 203 166   2 711 107 225 304 314 362 202 151 108 322 242 276 291
 284 478 230  99 203 201 418 164 243 166 300 336 121 321 319 411 150 263
 313 506 330 277 126 317 449 195]